import { Inter } from "next/font/google";
import "./globals.css";
import NotificationModal from "@/components/modals/notif-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-poppins">
        <main>{children}</main>
        <NotificationModal />
        <div id="portal"></div>
      </body>
    </html>
  );
}
